apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-global
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wormscott12397@gmail.com
    privateKeySecretRef:
      name: cert-manager-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
