name: Build and Push Docker images
run-name: ${{ github.actor }} is triggering Build and Push Docker images 🚀
on:
  push:
    branches:
      - release
concurrency: build_and_push_docker
jobs:
  build-anh-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current branch
        uses: actions/checkout@v3

      # Check if backend or frontend src folder has changes
      - name: Check if backend or frontend src folder has changes
        uses: dorny/paths-filter@v2
        id: detect-changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

      - name: Get new backend tag
        if: steps.detect-changes.outputs.backend == 'true'
        id: backend-image-tag
        run: |
          current=$(curl -s -S "https://registry.hub.docker.com/v2/repositories/${{ secrets.BE_DOCKERHUB_REPO }}/tags" |  
          jq '."results"[]["name"]' | sed -n 1p | cut -d'"' -f2)
          newImageTag=`expr $current + 1`
          echo "newImageTag=$(echo $newImageTag)" >> $GITHUB_OUTPUT
          # echo "::set-output name=newImageTag::$(echo $newImageTag)"

      - name: Get new frontend tag
        if: steps.detect-changes.outputs.frontend == 'true'
        id: frontend-image-tag
        run: |
          current=$(curl -s -S "https://registry.hub.docker.com/v2/repositories/${{ secrets.FE_DOCKERHUB_REPO }}/tags" |  
          jq '."results"[]["name"]' | sed -n 1p | cut -d'"' -f2)
          newImageTag=`expr $current + 1`
          echo "newImageTag=$(echo $newImageTag)" >> $GITHUB_OUTPUT
          # echo "::set-output name=newImageTag::$(echo $newImageTag)"

      # Login to DockerHub
      - name: Login to Docker Hub
        if: steps.detect-changes.outputs.frontend == 'true' || steps.detect-changes.outputs.backend == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # If have changes --> deploy
      - name: Run build and push image if changes exist
        if: steps.detect-changes.outputs.frontend == 'true' || steps.detect-changes.outputs.backend == 'true'
        run: |
          bash build_and_push.sh --fe-tag ${{ steps.frontend-image-tag.outputs.newImageTag }} --be-tag ${{ steps.backend-image-tag.outputs.newImageTag }}
          exit 0

      # If nothing changes, mark this job as failure
      - name: Failure Check
        if: steps.detect-changes.outputs.frontend == 'false' && steps.detect-changes.outputs.backend == 'false'
        run: |
          exit 1